version: '3'

services:
  hbbs:
    image: rustdesk/rustdesk-server
    container_name: rd-hbbs
    restart: always
    network_mode: "host"
    volumes:
      - ./hbbs:/root
    command: hbbs -r 101.133.147.45

  hbbr:
    image: rustdesk/rustdesk-server
    container_name: rd-hbbr
    restart: always
    network_mode: "host"
    volumes:
      - ./hbbr:/root
    command: hbbr
